version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  elixir:
    image: elixir
    restart: always
    command: bash -c "while true; do sleep 2; done"
    volumes:
    - ./:/mkhmac
    ports:
      - 4000:4000

